In [40]:
from os.path import join
from collections import defaultdict as ddict

root = "/run/media/ki/data/datasets/CUB_200_2011/"


path_to_id_map = dict()  # map from full image path to image id
with open(join(root, "images.txt"), "r") as f:
    for line in f:
        items = line.strip().split()
        path_to_id_map[join(root, "images", items[1])] = int(items[0])

attribute_labels_all = ddict(list)  # map from image id to a list of attribute labels
attribute_certainties_all = ddict(
    list
)  # map from image id to a list of attribute certainties
attribute_uncertain_labels_all = ddict(
    list
)  # map from image id to a list of attribute labels calibrated for uncertainty

# 1 = not visible, 2 = guessing, 3 = probably, 4 = definitely
uncertainty_map = {
    1: {1: 0, 2: 0.5, 3: 0.75, 4: 1},  # calibrate main label based on uncertainty label
    0: {1: 0, 2: 0.5, 3: 0.25, 4: 0},
}

with open(join(root + "/attributes/image_attribute_labels.txt"), "r") as f:
    for line in f:
        file_idx, attribute_idx, attribute_label, attribute_certainty = (
            line.strip().split()[:4]
        )
        attribute_label = int(attribute_label)
        attribute_certainty = int(attribute_certainty)
        uncertain_label = uncertainty_map[attribute_label][attribute_certainty]

        attribute_labels_all[int(file_idx)].append(attribute_label)
        attribute_uncertain_labels_all[int(file_idx)].append(uncertain_label)
        attribute_certainties_all[int(file_idx)].append(attribute_certainty)

In [41]:
with open("attributes.txt", "r") as f:
    attributes = f.readlines()

attributes = [a.split(" ")[1].strip().replace("::", "_") for a in attributes]

In [42]:
import pandas as pd

tmp = []

for index, lst in attribute_labels_all.items():
    if index == 0:
        continue

    r = {"index": index}
    r.update({attributes[i]: lst[i] for i in range(len(lst))})

    tmp.append(r)

In [43]:
df = pd.DataFrame(tmp)  # .set_index("index")

In [44]:
df

,index,has_bill_shape_curved_(up_or_down),has_bill_shape_dagger,has_bill_shape_hooked,has_bill_shape_needle,has_bill_shape_hooked_seabird,has_bill_shape_spatulate,has_bill_shape_all-purpose,has_bill_shape_cone,has_bill_shape_specialized,...,has_crown_color_pink,has_crown_color_orange,has_crown_color_black,has_crown_color_white,has_crown_color_red,has_crown_color_buff,has_wing_pattern_solid,has_wing_pattern_spotted,has_wing_pattern_striped,has_wing_pattern_multi-colored
0,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
3,4,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
4,5,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11783,11784,0,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
11784,11785,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,1,0,0,0,0
11785,11786,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,1,0
11786,11787,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
11787,11788,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,1,0,0,0,1

In [47]:
labels = [p.split("/")[-2] for p in path_to_id_map]
unique_labels = list(set(labels))
unique_labels.sort()

unique_labels

['001.Black_footed_Albatross',
 '002.Laysan_Albatross',
 '003.Sooty_Albatross',
 '004.Groove_billed_Ani',
 '005.Crested_Auklet',
 '006.Least_Auklet',
 '007.Parakeet_Auklet',
 '008.Rhinoceros_Auklet',
 '009.Brewer_Blackbird',
 '010.Red_winged_Blackbird',
 '011.Rusty_Blackbird',
 '012.Yellow_headed_Blackbird',
 '013.Bobolink',
 '014.Indigo_Bunting',
 '015.Lazuli_Bunting',
 '016.Painted_Bunting',
 '017.Cardinal',
 '018.Spotted_Catbird',
 '019.Gray_Catbird',
 '020.Yellow_breasted_Chat',
 '021.Eastern_Towhee',
 '022.Chuck_will_Widow',
 '023.Brandt_Cormorant',
 '024.Red_faced_Cormorant',
 '025.Pelagic_Cormorant',
 '026.Bronzed_Cowbird',
 '027.Shiny_Cowbird',
 '028.Brown_Creeper',
 '029.American_Crow',
 '030.Fish_Crow',
 '031.Black_billed_Cuckoo',
 '032.Mangrove_Cuckoo',
 '033.Yellow_billed_Cuckoo',
 '034.Gray_crowned_Rosy_Finch',
 '035.Purple_Finch',
 '036.Northern_Flicker',
 '037.Acadian_Flycatcher',
 '038.Great_Crested_Flycatcher',
 '039.Least_Flycatcher',
 '040.Olive_sided_Flycatcher',
 '041.Scissor_tailed_Flycatcher',
 '042.Vermilion_Flycatcher',
 '043.Yellow_bellied_Flycatcher',
 '044.Frigatebird',
 '045.Northern_Fulmar',
 '046.Gadwall',
 '047.American_Goldfinch',
 '048.European_Goldfinch',
 '049.Boat_tailed_Grackle',
 '050.Eared_Grebe',
 '051.Horned_Grebe',
 '052.Pied_billed_Grebe',
 '053.Western_Grebe',
 '054.Blue_Grosbeak',
 '055.Evening_Grosbeak',
 '056.Pine_Grosbeak',
 '057.Rose_breasted_Grosbeak',
 '058.Pigeon_Guillemot',
 '059.California_Gull',
 '060.Glaucous_winged_Gull',
 '061.Heermann_Gull',
 '062.Herring_Gull',
 '063.Ivory_Gull',
 '064.Ring_billed_Gull',
 '065.Slaty_backed_Gull',
 '066.Western_Gull',
 '067.Anna_Hummingbird',
 '068.Ruby_throated_Hummingbird',
 '069.Rufous_Hummingbird',
 '070.Green_Violetear',
 '071.Long_tailed_Jaeger',
 '072.Pomarine_Jaeger',
 '073.Blue_Jay',
 '074.Florida_Jay',
 '075.Green_Jay',
 '076.Dark_eyed_Junco',
 '077.Tropical_Kingbird',
 '078.Gray_Kingbird',
 '079.Belted_Kingfisher',
 '080.Green_Kingfisher',
 '081.Pied_Kingfisher',
 '082.Ringed_Kingfisher',
 '083.White_breasted_Kingfisher',
 '084.Red_legged_Kittiwake',
 '085.Horned_Lark',
 '086.Pacific_Loon',
 '087.Mallard',
 '088.Western_Meadowlark',
 '089.Hooded_Merganser',
 '090.Red_breasted_Merganser',
 '091.Mockingbird',
 '092.Nighthawk',
 '093.Clark_Nutcracker',
 '094.White_breasted_Nuthatch',
 '095.Baltimore_Oriole',
 '096.Hooded_Oriole',
 '097.Orchard_Oriole',
 '098.Scott_Oriole',
 '099.Ovenbird',
 '100.Brown_Pelican',
 '101.White_Pelican',
 '102.Western_Wood_Pewee',
 '103.Sayornis',
 '104.American_Pipit',
 '105.Whip_poor_Will',
 '106.Horned_Puffin',
 '107.Common_Raven',
 '108.White_necked_Raven',
 '109.American_Redstart',
 '110.Geococcyx',
 '111.Loggerhead_Shrike',
 '112.Great_Grey_Shrike',
 '113.Baird_Sparrow',
 '114.Black_throated_Sparrow',
 '115.Brewer_Sparrow',
 '116.Chipping_Sparrow',
 '117.Clay_colored_Sparrow',
 '118.House_Sparrow',
 '119.Field_Sparrow',
 '120.Fox_Sparrow',
 '121.Grasshopper_Sparrow',
 '122.Harris_Sparrow',
 '123.Henslow_Sparrow',
 '124.Le_Conte_Sparrow',
 '125.Lincoln_Sparrow',
 '126.Nelson_Sharp_tailed_Sparrow',
 '127.Savannah_Sparrow',
 '128.Seaside_Sparrow',
 '129.Song_Sparrow',
 '130.Tree_Sparrow',
 '131.Vesper_Sparrow',
 '132.White_crowned_Sparrow',
 '133.White_throated_Sparrow',
 '134.Cape_Glossy_Starling',
 '135.Bank_Swallow',
 '136.Barn_Swallow',
 '137.Cliff_Swallow',
 '138.Tree_Swallow',
 '139.Scarlet_Tanager',
 '140.Summer_Tanager',
 '141.Artic_Tern',
 '142.Black_Tern',
 '143.Caspian_Tern',
 '144.Common_Tern',
 '145.Elegant_Tern',
 '146.Forsters_Tern',
 '147.Least_Tern',
 '148.Green_tailed_Towhee',
 '149.Brown_Thrasher',
 '150.Sage_Thrasher',
 '151.Black_capped_Vireo',
 '152.Blue_headed_Vireo',
 '153.Philadelphia_Vireo',
 '154.Red_eyed_Vireo',
 '155.Warbling_Vireo',
 '156.White_eyed_Vireo',
 '157.Yellow_throated_Vireo',
 '158.Bay_breasted_Warbler',
 '159.Black_and_white_Warbler',
 '160.Black_throated_Blue_Warbler',
 '161.Blue_winged_Warbler',
 '162.Canada_Warbler',
 '163.Cape_May_Warbler',
 '164.Cerulean_Warbler',
 '165.Chestnut_sided_Warbler',
 '166.Golden_winged_Warbler',
 '167.Hooded_Warbler',
 '168.Kentucky_Warbler',
 '169.Magnolia_Warbler',
 '170.Mourning_Warbler',
 '171.Myrtle_Warbler',
 '172.Nashville_Warbler',
 '173.Orange_crowned_Warbler',
 '174.Palm_Warbler',
 '175.Pine_Warbler',
 '176.Prairie_Warbler',
 '177.Prothonotary_Warbler',
 '178.Swainson_Warbler',
 '179.Tennessee_Warbler',
 '180.Wilson_Warbler',
 '181.Worm_eating_Warbler',
 '182.Yellow_Warbler',
 '183.Northern_Waterthrush',
 '184.Louisiana_Waterthrush',
 '185.Bohemian_Waxwing',
 '186.Cedar_Waxwing',
 '187.American_Three_toed_Woodpecker',
 '188.Pileated_Woodpecker',
 '189.Red_bellied_Woodpecker',
 '190.Red_cockaded_Woodpecker',
 '191.Red_headed_Woodpecker',
 '192.Downy_Woodpecker',
 '193.Bewick_Wren',
 '194.Cactus_Wren',
 '195.Carolina_Wren',
 '196.House_Wren',
 '197.Marsh_Wren',
 '198.Rock_Wren',
 '199.Winter_Wren',
 '200.Common_Yellowthroat']

In [48]:
path_to_id_map

{'/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0046_18.jpg': 1,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0009_34.jpg': 2,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0002_55.jpg': 3,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0074_59.jpg': 4,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0014_89.jpg': 5,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0085_92.jpg': 6,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0031_100.jpg': 7,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0051_796103.jpg': 8,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0010_796097.jpg': 9,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0025_796057.jpg': 10,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0023_796059.jpg': 11,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0086_796062.jpg': 12,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0049_796063.jpg': 13,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0006_796065.jpg': 14,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0040_796066.jpg': 15,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0016_796067.jpg': 16,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0065_796068.jpg': 17,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0089_796069.jpg': 18,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0042_796071.jpg': 19,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0067_170.jpg': 20,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0060_796076.jpg': 21,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0090_796077.jpg': 22,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0056_796078.jpg': 23,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0061_796082.jpg': 24,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0008_796083.jpg': 25,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0033_796086.jpg': 26,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0024_796089.jpg': 27,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0005_796090.jpg': 28,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0026_796095.jpg': 29,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0080_796096.jpg': 30,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0047_796064.jpg': 31,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0017_796098.jpg': 32,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0064_796101.jpg': 33,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0076_417.jpg': 34,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0019_796104.jpg': 35,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0057_796106.jpg': 36,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0041_796108.jpg': 37,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0053_796109.jpg': 38,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0001_796111.jpg': 39,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0071_796113.jpg': 40,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0077_796114.jpg': 41,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0032_796115.jpg': 42,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0038_212.jpg': 43,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0037_796120.jpg': 44,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0082_796121.jpg': 45,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0079_796122.jpg': 46,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0050_796125.jpg': 47,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0078_796126.jpg': 48,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0036_796127.jpg': 49,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0045_796129.jpg': 50,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0039_796132.jpg': 51,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0088_796133.jpg': 52,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0068_796135.jpg': 53,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0003_796136.jpg': 54,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0007_796138.jpg': 55,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0069_796139.jpg': 56,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0035_796140.jpg': 57,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0063_796141.jpg': 58,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0058_796074.jpg': 59,
 '/run/media/ki/data/datasets/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0081_426.jpg': 60,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0002_1027.jpg': 61,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0003_1033.jpg': 62,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0082_524.jpg': 63,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0044_784.jpg': 64,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0070_788.jpg': 65,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0050_870.jpg': 66,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0071_792.jpg': 67,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0053_543.jpg': 68,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0081_800.jpg': 69,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0001_545.jpg': 70,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0023_1059.jpg': 71,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0065_809.jpg': 72,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0061_563.jpg': 73,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0085_564.jpg': 74,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0005_565.jpg': 75,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0060_777.jpg': 76,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0055_570.jpg': 77,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0025_571.jpg': 78,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0080_821.jpg': 79,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0092_834.jpg': 80,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0013_910.jpg': 81,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0091_602.jpg': 82,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0102_611.jpg': 83,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0099_869.jpg': 84,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0017_614.jpg': 85,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0047_619.jpg': 86,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0035_876.jpg': 87,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0098_621.jpg': 88,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0088_883.jpg': 89,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0034_628.jpg': 90,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0104_630.jpg': 91,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0058_637.jpg': 92,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0028_643.jpg': 93,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0033_658.jpg': 94,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0075_668.jpg': 95,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0076_671.jpg': 96,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0096_673.jpg': 97,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0064_674.jpg': 98,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0039_924.jpg': 99,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0049_918.jpg': 100,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0012_696.jpg': 101,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0056_500.jpg': 102,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0037_699.jpg': 103,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0006_702.jpg': 104,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0073_927.jpg': 105,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0042_801.jpg': 106,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0004_930.jpg': 107,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0093_725.jpg': 108,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0068_726.jpg': 109,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0040_472.jpg': 110,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0100_735.jpg': 111,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0021_737.jpg': 112,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0029_482.jpg': 113,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0059_488.jpg': 114,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0018_492.jpg': 115,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0083_756.jpg': 116,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0094_1013.jpg': 117,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0103_504.jpg': 118,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0079_506.jpg': 119,
 '/run/media/ki/data/datasets/CUB_200_2011/images/002.Laysan_Albatross/Laysan_Albatross_0051_1020.jpg': 120,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0038_1065.jpg': 121,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0031_1066.jpg': 122,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0001_1071.jpg': 123,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0016_1075.jpg': 124,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0043_1076.jpg': 125,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0003_1078.jpg': 126,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0077_1080.jpg': 127,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0063_1101.jpg': 128,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0044_1105.jpg': 129,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0071_1116.jpg': 130,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0070_796346.jpg': 131,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0030_1122.jpg': 132,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0054_796347.jpg': 133,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0033_1128.jpg': 134,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0048_1130.jpg': 135,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0032_1149.jpg': 136,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0034_1154.jpg': 137,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0055_1160.jpg': 138,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0024_1161.jpg': 139,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0045_1162.jpg': 140,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0073_1171.jpg': 141,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0074_1221.jpg': 142,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0021_796339.jpg': 143,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0005_796342.jpg': 144,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0064_796343.jpg': 145,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0042_1210.jpg': 146,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0046_1211.jpg': 147,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0017_796349.jpg': 148,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0049_796350.jpg': 149,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0050_796351.jpg': 150,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0075_796352.jpg': 151,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0068_796353.jpg': 152,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0057_796354.jpg': 153,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0010_796355.jpg': 154,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0029_796357.jpg': 155,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0069_796358.jpg': 156,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0020_796359.jpg': 157,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0058_796360.jpg': 158,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0025_796361.jpg': 159,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0041_796364.jpg': 160,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0076_796365.jpg': 161,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0004_796366.jpg': 162,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0065_796367.jpg': 163,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0072_796371.jpg': 164,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0007_796372.jpg': 165,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0014_796373.jpg': 166,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0051_796374.jpg': 167,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0040_796375.jpg': 168,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0067_796376.jpg': 169,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0066_796382.jpg': 170,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0036_796387.jpg': 171,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0079_796389.jpg': 172,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0006_796390.jpg': 173,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0019_796391.jpg': 174,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0002_796395.jpg': 175,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0022_796398.jpg': 176,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0023_796401.jpg': 177,
 '/run/media/ki/data/datasets/CUB_200_2011/images/003.Sooty_Albatross/Sooty_Albatross_0013_796402.jpg': 178,

In [49]:
df["class"] = [unique_labels.index(l) for l in labels]

In [50]:
df

,index,has_bill_shape_curved_(up_or_down),has_bill_shape_dagger,has_bill_shape_hooked,has_bill_shape_needle,has_bill_shape_hooked_seabird,has_bill_shape_spatulate,has_bill_shape_all-purpose,has_bill_shape_cone,has_bill_shape_specialized,...,has_crown_color_orange,has_crown_color_black,has_crown_color_white,has_crown_color_red,has_crown_color_buff,has_wing_pattern_solid,has_wing_pattern_spotted,has_wing_pattern_striped,has_wing_pattern_multi-colored,class
0,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
3,4,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
4,5,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11783,11784,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,199
11784,11785,0,0,0,0,0,0,1,0,0,...,0,0,1,0,1,0,0,0,0,199
11785,11786,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,1,0,199
11786,11787,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,199
11787,11788,0,0,0,0,0,0,1,0,0,...,0,0,1,0,1,0,0,0,1,199

In [8]:
id_to_path_map = {v: k for k, v in path_to_id_map.items()}
df["path"] = df["index"].apply(id_to_path_map.get)

In [9]:
df

,index,has_bill_shape_curved_(up_or_down),has_bill_shape_dagger,has_bill_shape_hooked,has_bill_shape_needle,has_bill_shape_hooked_seabird,has_bill_shape_spatulate,has_bill_shape_all-purpose,has_bill_shape_cone,has_bill_shape_specialized,...,has_crown_color_black,has_crown_color_white,has_crown_color_red,has_crown_color_buff,has_wing_pattern_solid,has_wing_pattern_spotted,has_wing_pattern_striped,has_wing_pattern_multi-colored,class,path
0,1,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,/run/media/ki/data/datasets/CUB_200_2011/image...
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,/run/media/ki/data/datasets/CUB_200_2011/image...
2,3,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,/run/media/ki/data/datasets/CUB_200_2011/image...
3,4,0,0,0,0,1,0,0,0,0,...,0,1,0,0,1,0,0,0,0,/run/media/ki/data/datasets/CUB_200_2011/image...
4,5,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,/run/media/ki/data/datasets/CUB_200_2011/image...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11783,11784,0,1,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,/run/media/ki/data/datasets/CUB_200_2011/image...
11784,11785,0,0,0,0,0,0,1,0,0,...,0,1,0,1,0,0,0,0,0,/run/media/ki/data/datasets/CUB_200_2011/image...
11785,11786,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,1,0,0,/run/media/ki/data/datasets/CUB_200_2011/image...
11786,11787,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,/run/media/ki/data/datasets/CUB_200_2011/image...
11787,11788,0,0,0,0,0,0,1,0,0,...,0,1,0,1,0,0,0,1,0,/run/media/ki/data/datasets/CUB_200_2011/image...

In [10]:
att_names = attributes

mymap = lambda x: 1 if x else 0

for i in range(200):
    items = df[df["class"] == i]
    att_values = items[att_names].sum() > 10
    df.loc[df["class"] == i, att_names] = [mymap(t) for t in att_values.values.tolist()]

In [11]:
df

,index,has_bill_shape_curved_(up_or_down),has_bill_shape_dagger,has_bill_shape_hooked,has_bill_shape_needle,has_bill_shape_hooked_seabird,has_bill_shape_spatulate,has_bill_shape_all-purpose,has_bill_shape_cone,has_bill_shape_specialized,...,has_crown_color_black,has_crown_color_white,has_crown_color_red,has_crown_color_buff,has_wing_pattern_solid,has_wing_pattern_spotted,has_wing_pattern_striped,has_wing_pattern_multi-colored,class,path
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,/run/media/ki/data/datasets/CUB_200_2011/image...
1,2,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,/run/media/ki/data/datasets/CUB_200_2011/image...
2,3,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,/run/media/ki/data/datasets/CUB_200_2011/image...
3,4,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,/run/media/ki/data/datasets/CUB_200_2011/image...
4,5,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,/run/media/ki/data/datasets/CUB_200_2011/image...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11783,11784,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,/run/media/ki/data/datasets/CUB_200_2011/image...
11784,11785,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,/run/media/ki/data/datasets/CUB_200_2011/image...
11785,11786,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,/run/media/ki/data/datasets/CUB_200_2011/image...
11786,11787,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,/run/media/ki/data/datasets/CUB_200_2011/image...
11787,11788,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0,/run/media/ki/data/datasets/CUB_200_2011/image...

In [12]:
selected_attributes = [
    1,
    4,
    6,
    7,
    10,
    14,
    15,
    20,
    21,
    23,
    25,
    29,
    30,
    35,
    36,
    38,
    40,
    44,
    45,
    50,
    51,
    53,
    54,
    56,
    57,
    59,
    63,
    64,
    69,
    70,
    72,
    75,
    80,
    84,
    90,
    91,
    93,
    99,
    101,
    106,
    110,
    111,
    116,
    117,
    119,
    125,
    126,
    131,
    132,
    134,
    145,
    149,
    151,
    152,
    153,
    157,
    158,
    163,
    164,
    168,
    172,
    178,
    179,
    181,
    183,
    187,
    188,
    193,
    194,
    196,
    198,
    202,
    203,
    208,
    209,
    211,
    212,
    213,
    218,
    220,
    221,
    225,
    235,
    236,
    238,
    239,
    240,
    242,
    243,
    244,
    249,
    253,
    254,
    259,
    260,
    262,
    268,
    274,
    277,
    283,
    289,
    292,
    293,
    294,
    298,
    299,
    304,
    305,
    308,
    309,
    310,
    311,
]

In [13]:
# they start to count at 1, us suspect, so we substract 1
sel_att_names = [att_names[i] for i in selected_attributes]

In [14]:
cut_df = df[["index", *sel_att_names, "class", "path"]].set_index("index")

In [15]:
cut_df.to_csv("cub-labels.csv")

In [16]:
sel_att_names

['has_bill_shape_dagger',
 'has_bill_shape_hooked_seabird',
 'has_bill_shape_all-purpose',
 'has_bill_shape_cone',
 'has_wing_color_brown',
 'has_wing_color_grey',
 'has_wing_color_yellow',
 'has_wing_color_black',
 'has_wing_color_white',
 'has_wing_color_buff',
 'has_upperparts_color_brown',
 'has_upperparts_color_grey',
 'has_upperparts_color_yellow',
 'has_upperparts_color_black',
 'has_upperparts_color_white',
 'has_upperparts_color_buff',
 'has_underparts_color_brown',
 'has_underparts_color_grey',
 'has_underparts_color_yellow',
 'has_underparts_color_black',
 'has_underparts_color_white',
 'has_underparts_color_buff',
 'has_breast_pattern_solid',
 'has_breast_pattern_striped',
 'has_breast_pattern_multi-colored',
 'has_back_color_brown',
 'has_back_color_grey',
 'has_back_color_yellow',
 'has_back_color_black',
 'has_back_color_white',
 'has_back_color_buff',
 'has_tail_shape_notched_tail',
 'has_upper_tail_color_brown',
 'has_upper_tail_color_grey',
 'has_upper_tail_color_black',
 'has_upper_tail_color_white',
 'has_upper_tail_color_buff',
 'has_head_pattern_eyebrow',
 'has_head_pattern_plain',
 'has_breast_color_brown',
 'has_breast_color_grey',
 'has_breast_color_yellow',
 'has_breast_color_black',
 'has_breast_color_white',
 'has_breast_color_buff',
 'has_throat_color_grey',
 'has_throat_color_yellow',
 'has_throat_color_black',
 'has_throat_color_white',
 'has_throat_color_buff',
 'has_eye_color_black',
 'has_bill_length_about_the_same_as_head',
 'has_bill_length_shorter_than_head',
 'has_forehead_color_blue',
 'has_forehead_color_brown',
 'has_forehead_color_grey',
 'has_forehead_color_yellow',
 'has_forehead_color_black',
 'has_forehead_color_white',
 'has_under_tail_color_brown',
 'has_under_tail_color_grey',
 'has_under_tail_color_black',
 'has_under_tail_color_white',
 'has_under_tail_color_buff',
 'has_nape_color_brown',
 'has_nape_color_grey',
 'has_nape_color_yellow',
 'has_nape_color_black',
 'has_nape_color_white',
 'has_nape_color_buff',
 'has_belly_color_brown',
 'has_belly_color_grey',
 'has_belly_color_yellow',
 'has_belly_color_black',
 'has_belly_color_white',
 'has_belly_color_buff',
 'has_wing_shape_rounded-wings',
 'has_wing_shape_pointed-wings',
 'has_size_small_(5_-_9_in)',
 'has_size_medium_(9_-_16_in)',
 'has_size_very_small_(3_-_5_in)',
 'has_shape_duck-like',
 'has_shape_perching-like',
 'has_back_pattern_solid',
 'has_back_pattern_striped',
 'has_back_pattern_multi-colored',
 'has_tail_pattern_solid',
 'has_tail_pattern_striped',
 'has_tail_pattern_multi-colored',
 'has_belly_pattern_solid',
 'has_primary_color_brown',
 'has_primary_color_grey',
 'has_primary_color_yellow',
 'has_primary_color_black',
 'has_primary_color_white',
 'has_primary_color_buff',
 'has_leg_color_grey',
 'has_leg_color_black',
 'has_leg_color_buff',
 'has_bill_color_grey',
 'has_bill_color_black',
 'has_bill_color_buff',
 'has_crown_color_blue',
 'has_crown_color_brown',
 'has_crown_color_grey',
 'has_crown_color_yellow',
 'has_crown_color_black',
 'has_crown_color_white',
 'has_wing_pattern_solid',
 'has_wing_pattern_spotted',
 'has_wing_pattern_striped',
 'has_wing_pattern_multi-colored']

In [21]:
cut_df[[*sel_att_names]].corr()

,has_bill_shape_dagger,has_bill_shape_hooked_seabird,has_bill_shape_all-purpose,has_bill_shape_cone,has_wing_color_brown,has_wing_color_grey,has_wing_color_yellow,has_wing_color_black,has_wing_color_white,has_wing_color_buff,...,has_crown_color_blue,has_crown_color_brown,has_crown_color_grey,has_crown_color_yellow,has_crown_color_black,has_crown_color_white,has_wing_pattern_solid,has_wing_pattern_spotted,has_wing_pattern_striped,has_wing_pattern_multi-colored
has_bill_shape_dagger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
has_bill_shape_hooked_seabird,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
has_bill_shape_all-purpose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
has_bill_shape_cone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
has_wing_color_brown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
has_crown_color_white,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
has_wing_pattern_solid,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
has_wing_pattern_spotted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
has_wing_pattern_striped,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
has_wing_pattern_multi-colored,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
cut_df[cut_df == 0] = -1

In [32]:
cut_df[[*sel_att_names]].corr()

,has_bill_shape_dagger,has_bill_shape_hooked_seabird,has_bill_shape_all-purpose,has_bill_shape_cone,has_wing_color_brown,has_wing_color_grey,has_wing_color_yellow,has_wing_color_black,has_wing_color_white,has_wing_color_buff,...,has_crown_color_blue,has_crown_color_brown,has_crown_color_grey,has_crown_color_yellow,has_crown_color_black,has_crown_color_white,has_wing_pattern_solid,has_wing_pattern_spotted,has_wing_pattern_striped,has_wing_pattern_multi-colored
has_bill_shape_dagger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
has_bill_shape_hooked_seabird,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
has_bill_shape_all-purpose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
has_bill_shape_cone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
has_wing_color_brown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
has_crown_color_white,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
has_wing_pattern_solid,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
has_wing_pattern_spotted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
has_wing_pattern_striped,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
has_wing_pattern_multi-colored,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
import pandas as pd

df = pd.read_csv("cub-labels.csv")

In [5]:
df

,index,has_bill_shape_dagger,has_bill_shape_hooked_seabird,has_bill_shape_all-purpose,has_bill_shape_cone,has_wing_color_brown,has_wing_color_grey,has_wing_color_yellow,has_wing_color_black,has_wing_color_white,...,has_crown_color_grey,has_crown_color_yellow,has_crown_color_black,has_crown_color_white,has_wing_pattern_solid,has_wing_pattern_spotted,has_wing_pattern_striped,has_wing_pattern_multi-colored,class,path
0,1,0,1,0,0,1,1,0,1,0,...,1,0,0,0,1,0,1,1,0,CUB_200_2011/images/001.Black_footed_Albatross...
1,2,0,1,0,0,1,1,0,1,0,...,1,0,0,0,1,0,1,1,0,CUB_200_2011/images/001.Black_footed_Albatross...
2,3,0,1,0,0,1,1,0,1,0,...,1,0,0,0,1,0,1,1,0,CUB_200_2011/images/001.Black_footed_Albatross...
3,4,0,1,0,0,1,1,0,1,0,...,1,0,0,0,1,0,1,1,0,CUB_200_2011/images/001.Black_footed_Albatross...
4,5,0,1,0,0,1,1,0,1,0,...,1,0,0,0,1,0,1,1,0,CUB_200_2011/images/001.Black_footed_Albatross...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11783,11784,0,0,1,0,1,1,1,0,0,...,1,0,0,1,1,0,0,1,199,CUB_200_2011/images/200.Common_Yellowthroat/Co...
11784,11785,0,0,1,0,1,1,1,0,0,...,1,0,0,1,1,0,0,1,199,CUB_200_2011/images/200.Common_Yellowthroat/Co...
11785,11786,0,0,1,0,1,1,1,0,0,...,1,0,0,1,1,0,0,1,199,CUB_200_2011/images/200.Common_Yellowthroat/Co...
11786,11787,0,0,1,0,1,1,1,0,0,...,1,0,0,1,1,0,0,1,199,CUB_200_2011/images/200.Common_Yellowthroat/Co...
11787,11788,0,0,1,0,1,1,1,0,0,...,1,0,0,1,1,0,0,1,199,CUB_200_2011/images/200.Common_Yellowthroat/Co...

In [6]:
atts = [a for a in df.columns if "has_" in a]

In [7]:
classes = df["class"].unique()

df_tmp = df.set_index("class")

for clazz in classes:
    is_set = []

    item = df_tmp.loc[clazz].head(1)
    for att in atts:
        if item[att].any() == 1:
            is_set.append(
                att.replace("multi-colored", "multi_colored").replace(
                    "all-purpose", "all_purpose"
                )
            )

    print(f"{clazz} -> {' and '.join(is_set)}")

0 -> has_bill_shape_hooked_seabird and has_wing_color_brown and has_wing_color_grey and has_wing_color_black and has_wing_color_buff and has_upperparts_color_brown and has_upperparts_color_grey and has_upperparts_color_black and has_upperparts_color_buff and has_underparts_color_brown and has_underparts_color_grey and has_breast_pattern_solid and has_back_color_brown and has_back_color_grey and has_back_color_black and has_back_color_buff and has_upper_tail_color_brown and has_head_pattern_plain and has_breast_color_brown and has_breast_color_grey and has_throat_color_grey and has_throat_color_black and has_throat_color_buff and has_eye_color_black and has_bill_length_about_the_same_as_head and has_forehead_color_grey and has_forehead_color_white and has_under_tail_color_brown and has_under_tail_color_grey and has_under_tail_color_black and has_nape_color_brown and has_nape_color_grey and has_nape_color_buff and has_belly_color_grey and has_wing_shape_pointed-wings and has_size_medium_(9_-_16_in) and has_shape_duck-like and has_back_pattern_solid and has_back_pattern_multi_colored and has_tail_pattern_solid and has_tail_pattern_multi_colored and has_belly_pattern_solid and has_primary_color_brown and has_primary_color_grey and has_primary_color_black and has_primary_color_buff and has_bill_color_grey and has_bill_color_black and has_bill_color_buff and has_crown_color_brown and has_crown_color_grey and has_wing_pattern_solid and has_wing_pattern_striped and has_wing_pattern_multi_colored
1 -> has_bill_shape_hooked_seabird and has_wing_color_brown and has_wing_color_black and has_upperparts_color_brown and has_upperparts_color_black and has_upperparts_color_white and has_underparts_color_white and has_breast_pattern_solid and has_back_color_brown and has_back_color_black and has_back_color_white and has_upper_tail_color_black and has_upper_tail_color_white and has_head_pattern_plain and has_breast_color_white and has_throat_color_white and has_eye_color_black and has_bill_length_about_the_same_as_head and has_forehead_color_white and has_under_tail_color_black and has_under_tail_color_white and has_nape_color_white and has_belly_color_white and has_size_medium_(9_-_16_in) and has_shape_duck-like and has_back_pattern_solid and has_tail_pattern_solid and has_tail_pattern_multi_colored and has_belly_pattern_solid and has_primary_color_brown and has_primary_color_grey and has_primary_color_black and has_primary_color_white and has_bill_color_grey and has_bill_color_buff and has_crown_color_white and has_wing_pattern_solid
2 -> has_bill_shape_hooked_seabird and has_wing_color_brown and has_wing_color_grey and has_wing_color_black and has_upperparts_color_grey and has_upperparts_color_black and has_underparts_color_grey and has_underparts_color_black and has_breast_pattern_solid and has_back_color_grey and has_upper_tail_color_grey and has_head_pattern_plain and has_breast_color_grey and has_breast_color_black and has_throat_color_grey and has_throat_color_black and has_eye_color_black and has_bill_length_about_the_same_as_head and has_forehead_color_brown and has_forehead_color_black and has_under_tail_color_grey and has_under_tail_color_black and has_nape_color_grey and has_belly_color_grey and has_belly_color_black and has_size_small_(5_-_9_in) and has_size_medium_(9_-_16_in) and has_back_pattern_solid and has_tail_pattern_solid and has_belly_pattern_solid and has_primary_color_brown and has_primary_color_grey and has_primary_color_black and has_primary_color_buff and has_bill_color_grey and has_bill_color_black and has_crown_color_brown and has_crown_color_grey and has_crown_color_black and has_wing_pattern_solid
3 -> has_bill_shape_cone and has_wing_color_black and has_upperparts_color_black and has_underparts_color_black and has_breast_pattern_solid and has_back_color_black and has_tail_shape_notched_tail and has_upper_tail_color_black and has_head_pattern_plain and has_breast_color_black and has_throat_color_black and has_eye_color_black and has_bill_length_about_the_same_as_head and has_bill_length_shorter_than_head and has_forehead_color_black and has_under_tail_color_black and has_nape_color_black and has_belly_color_black and has_wing_shape_rounded-wings and has_size_small_(5_-_9_in) and has_size_very_small_(3_-_5_in) and has_shape_perching-like and has_back_pattern_solid and has_tail_pattern_solid and has_belly_pattern_solid and has_primary_color_black and has_leg_color_black and has_bill_color_grey and has_bill_color_black and has_crown_color_black and has_wing_pattern_solid
4 -> has_bill_shape_cone and has_wing_color_grey and has_wing_color_black and has_upperparts_color_black and has_underparts_color_grey and has_underparts_color_black and has_breast_pattern_solid and has_back_color_black and has_upper_tail_color_black and has_breast_color_grey and has_breast_color_black and has_throat_color_grey and has_throat_color_black and has_eye_color_black and has_bill_length_shorter_than_head and has_forehead_color_black and has_under_tail_color_black and has_nape_color_black and has_belly_color_grey and has_belly_color_black and has_size_medium_(9_-_16_in) and has_back_pattern_solid and has_tail_pattern_solid and has_belly_pattern_solid and has_primary_color_grey and has_primary_color_black and has_leg_color_grey and has_crown_color_black and has_wing_pattern_solid
5 -> has_bill_shape_cone and has_wing_color_grey and has_wing_color_black and has_wing_color_white and has_upperparts_color_grey and has_upperparts_color_black and has_upperparts_color_white and has_underparts_color_grey and has_underparts_color_black and has_underparts_color_white and has_breast_pattern_striped and has_back_color_black and has_upper_tail_color_black and has_breast_color_grey and has_breast_color_black and has_breast_color_white and has_throat_color_black and has_throat_color_white and has_eye_color_black and has_bill_length_shorter_than_head and has_forehead_color_grey and has_forehead_color_black and has_under_tail_color_black and has_under_tail_color_white and has_nape_color_grey and has_nape_color_black and has_belly_color_grey and has_belly_color_black and has_belly_color_white and has_size_small_(5_-_9_in) and has_size_medium_(9_-_16_in) and has_back_pattern_solid and has_primary_color_grey and has_primary_color_black and has_primary_color_white and has_leg_color_grey and has_leg_color_black and has_bill_color_black and has_crown_color_grey and has_crown_color_black and has_wing_pattern_striped
6 -> has_bill_shape_cone and has_wing_color_grey and has_wing_color_black and has_upperparts_color_grey and has_upperparts_color_black and has_underparts_color_grey and has_underparts_color_white and has_breast_pattern_solid and has_breast_pattern_multi_colored and has_back_color_grey and has_back_color_black and has_upper_tail_color_grey and has_upper_tail_color_black and has_head_pattern_plain and has_breast_color_grey and has_breast_color_black and has_breast_color_white and has_throat_color_grey and has_throat_color_black and has_throat_color_white and has_eye_color_black and has_bill_length_shorter_than_head and has_forehead_color_grey and has_forehead_color_black and has_under_tail_color_black and has_under_tail_color_white and has_nape_color_grey and has_nape_color_black and has_belly_color_white and has_size_small_(5_-_9_in) and has_size_medium_(9_-_16_in) and has_shape_duck-like and has_back_pattern_solid and has_tail_pattern_solid and has_belly_pattern_solid and has_primary_color_grey and has_primary_color_black and has_primary_color_white and has_leg_color_grey and has_crown_color_grey and has_crown_color_black and has_wing_pattern_solid
7 -> has_bill_shape_all_purpose and has_wing_color_brown and has_wing_color_black and has_upperparts_color_brown and has_upperparts_color_black and has_underparts_color_grey and has_breast_pattern_solid and has_back_color_brown and has_back_color_black and has_upper_tail_color_black and has_head_pattern_eyebrow and has_head_pattern_plain and has_breast_color_grey and has_breast_color_black and has_throat_color_grey and has_throat_color_black and has_eye_color_black and has_bill_length_about_the_same_as_head and has_bill_length_shorter_than_head and has_forehead_color_grey and has_forehead_color_black and has_under_tail_color_black and has_nape_color_brown and has_nape_color_grey and has_nape_color_black and has_belly_color_grey and has_wing_shape_rounded-wings and has_size_medium_(9_-_16_in) and has_shape_duck-like and has_back_pattern_solid and has_tail_pattern_solid and has_belly_pattern_solid and has_primary_color_brown and has_primary_color_grey and has_primary_color_black and has_crown_color_grey and has_crown_color_black and has_wing_pattern_solid
8 -> has_bill_shape_all_purpose and has_bill_shape_cone and has_wing_color_black and has_upperparts_color_black and has_underparts_color_black and has_breast_pattern_solid and has_back_color_black and has_tail_shape_notched_tail and has_upper_tail_color_black and has_head_pattern_plain and has_breast_color_black and has_throat_color_black and has_eye_color_black and has_bill_length_about_the_same_as_head and has_bill_length_shorter_than_head and has_forehead_color_black and has_under_tail_color_black and has_nape_color_black and has_belly_color_black and has_wing_shape_rounded-wings and has_size_small_(5_-_9_in) and has_size_medium_(9_-_16_in) and has_shape_perching-like and has_back_pattern_solid and has_tail_pattern_solid and has_belly_pattern_solid and has_primary_color_black and has_leg_color_grey and has_leg_color_black and has_bill_color_black and has_crown_color_black and has_wing_pattern_solid
9 -> has_bill_shape_dagger and has_bill_shape_all_purpose and has_bill_shape_cone and has_wing_color_yellow and has_wing_color_black and has_wing_color_white and has_upperparts_color_black and has_underparts_color_black and has_breast_pattern_solid and has_back_color_black and has_tail_shape_notched_tail and has_upper_tail_color_black and has_head_pattern_plain and has_breast_color_black and has_throat_color_black and has_eye_color_black and has_bill_length_about_the_same_as_head and has_bill_length_shorter_than_head and has_forehead_color_black and has_under_tail_color_black and has_nape_color_black and has_belly_color_black and has_wing_shape_rounded-wings and has_size_small_(5_-_9_in) and has_shape_perching-like and has_back_pattern_solid and has_tail_pattern_solid and has_belly_pattern_solid and has_primary_color_black and has_leg_color_grey and has_leg_color_black and has_bill_color_grey and has_bill_color_black and has_crown_color_black and has_wing_pattern_multi_colored
10 -> has_bill_shape_all_purpose and has_bill_shape_cone and has_wing_color_brown and has_wing_color_grey and has_wing_color_black and has_upperparts_color_brown and has_upperparts_color_black and has_underparts_color_brown and has_underparts_color_grey and has_underparts_color_black and has_underparts_color_buff and has_breast_pattern_solid and has_back_color_brown and has_back_color_grey and has_back_color_black and has_tail_shape_notched_tail and has_upper_tail_color_black and has_head_pattern_eyebrow and has_head_pattern_plain and has_breast_color_brown and has_breast_color_grey and has_breast_color_black and has_breast_color_buff and has_throat_color_black and has_throat_color_buff and has_eye_color_black and has_bill_length_about_the_same_as_head and has_bill_length_shorter_than_head and has_forehead_color_brown and has_forehead_color_black and has_under_tail_color_black and has_nape_color_brown and has_nape_color_black and has_nape_color_buff and has_belly_color_brown and has_belly_color_grey and has_belly_color_black and has_belly_color_buff and has_wing_shape_rounded-wings and has_wing_shape_pointed-wings and has_size_small_(5_-_9_in) and has_shape_perching-like and has_back_pattern_solid and has_back_pattern_striped and has_back_pattern_multi_colored and has_tail_pattern_solid and has_belly_pattern_solid and has_primary_color_brown and has_primary_color_black and has_primary_color_buff and has_leg_color_grey and has_leg_color_black and has_bill_color_grey and has_bill_color_black and has_crown_color_brown and has_crown_color_black and has_wing_pattern_solid and has_wing_pattern_striped and has_wing_pattern_multi_colored
11 -> has_bill_shape_all_purpose and has_bill_shape_cone and has_wing_color_black and has_wing_color_white and has_upperparts_color_black and has_underparts_color_yellow and has_underparts_color_black and has_breast_pattern_solid and has_breast_pattern_multi_colored and has_back_color_black and has_tail_shape_notched_tail and has_upper_tail_color_black and has_head_pattern_plain and has_breast_color_yellow and has_breast_color_black and has_throat_color_yellow and has_eye_color_black and has_bill_length_shorter_than_head and has_forehead_color_yellow and has_under_tail_color_black and has_nape_color_yellow and has_nape_color_black and has_belly_color_yellow and has_belly_color_black and has_wing_shape_rounded-wings and has_size_small_(5_-_9_in) and has_size_medium_(9_-_16_in) and has_shape_perching-like and has_back_pattern_solid and has_tail_pattern_solid and has_belly_pattern_solid and has_primary_color_yellow and has_primary_color_black and has_leg_color_grey and has_leg_color_black and has_bill_color_grey and has_bill_color_black and has_crown_color_yellow and has_wing_pattern_solid and has_wing_pattern_multi_colored
12 -> has_bill_shape_cone and has_wing_color_grey and has_wing_color_black and has_wing_color_white and has_upperparts_color_grey and has_upperparts_color_black and has_upperparts_color_white and has_underparts_color_black and has_breast_pattern_solid and has_back_color_grey and has_back_color_black and has_back_color_white and has_tail_shape_notched_tail and has_upper_tail_color_grey and has_upper_tail_color_black and has_upper_tail_color_white and has_head_pattern_plain and has_breast_color_black and has_throat_color_black and has_eye_color_black and has_bill_length_shorter_than_head and has_forehead_color_black and has_under_tail_color_black and has_under_tail_color_white and has_nape_color_yellow and has_nape_color_black and has_nape_color_white and has_nape_color_buff and has_belly_color_black and has_wing_shape_rounded-wings and has_wing_shape_pointed-wings and has_size_small_(5_-_9_in) and has_size_very_small_(3_-_5_in) and has_shape_perching-like and has_back_pattern_solid and has_back_pattern_striped and has_back_pattern_multi_colored and has_tail_pattern_solid and has_tail_pattern_multi_colored and has_belly_pattern_solid and has_primary_color_black and has_primary_color_white and has_leg_color_grey and has_leg_color_black and has_leg_color_buff and has_bill_color_grey and has_bill_color_black and has_crown_color_black and has_crown_color_white and has_wing_pattern_striped and has_wing_pattern_multi_colored
13 -> has_bill_shape_all_purpose and has_bill_shape_cone and has_wing_color_grey and has_wing_color_black and has_upperparts_color_grey and has_upperparts_color_black and has_breast_pattern_solid and has_tail_shape_notched_tail and has_upper_tail_color_grey and has_upper_tail_color_black and has_head_pattern_plain and has_eye_color_black and has_bill_length_shorter_than_head and has_forehead_color_blue and has_under_tail_color_grey and has_under_tail_color_black and has_wing_shape_rounded-wings and has_size_small_(5_-_9_in) and has_size_very_small_(3_-_5_in) and has_shape_perching-like and has_back_pattern_solid and has_back_pattern_multi_colored and has_tail_pattern_solid and has_tail_pattern_multi_colored and has_belly_pattern_solid and has_leg_color_grey and has_leg_color_black and has_bill_color_grey and has_crown_color_blue and has_wing_pattern_striped and has_wing_pattern_multi_colored
14 -> has_bill_shape_all_purpose and has_bill_shape_cone and has_wing_color_grey and has_wing_color_black and has_wing_color_white and has_upperparts_color_grey and has_upperparts_color_black and has_upperparts_color_white and has_underparts_color_white and has_underparts_color_buff and has_breast_pattern_solid and has_breast_pattern_multi_colored and has_back_color_grey and has_back_color_black and has_tail_shape_notched_tail and has_upper_tail_color_black and has_head_pattern_plain and has_breast_color_white and has_breast_color_buff and has_eye_color_black and has_bill_length_shorter_than_head and has_forehead_color_blue and has_under_tail_color_grey and has_under_tail_color_black and has_belly_color_white and has_belly_color_buff and has_wing_shape_rounded-wings and has_size_small_(5_-_9_in) and has_size_very_small_(3_-_5_in) and has_shape_perching-like and has_back_pattern_striped and has_back_pattern_multi_colored and has_tail_pattern_solid and has_tail_pattern_multi_colored and has_belly_pattern_solid and has_primary_color_grey and has_primary_color_black and has_primary_color_white and has_primary_color_buff and has_leg_color_grey and has_leg_color_black and has_bill_color_grey and has_bill_color_black and has_crown_color_blue and has_wing_pattern_striped and has_wing_pattern_multi_colored
15 -> has_bill_shape_all_purpose and has_bill_shape_cone and has_wing_color_brown and has_wing_color_yellow and has_upperparts_color_yellow and has_breast_pattern_solid and has_back_color_yellow and has_tail_shape_notched_tail and has_head_pattern_plain and has_eye_color_black and has_bill_length_shorter_than_head and has_forehead_color_blue and has_under_tail_color_grey and has_wing_shape_rounded-wings and has_size_small_(5_-_9_in) and has_shape_perching-like and has_back_pattern_solid and has_back_pattern_multi_colored and has_tail_pattern_solid and has_tail_pattern_multi_colored and has_belly_pattern_solid and has_primary_color_yellow and has_leg_color_grey and has_bill_color_grey and has_bill_color_black and has_crown_color_blue and has_wing_pattern_striped and has_wing_pattern_multi_colored
16 -> has_bill_shape_cone and has_wing_color_grey and has_wing_color_black and has_upperparts_color_grey and has_breast_pattern_solid and has_breast_pattern_multi_colored and has_tail_shape_notched_tail and has_throat_color_black and has_eye_color_black and has_bill_length_shorter_than_head and has_forehead_color_black and has_wing_shape_rounded-wings and has_size_small_(5_-_9_in) and has_size_very_small_(3_-_5_in) and has_shape_perching-like and has_back_pattern_solid and has_back_pattern_multi_colored and has_tail_pattern_solid and has_tail_pattern_multi_colored and has_belly_pattern_solid and has_leg_color_grey and has_leg_color_buff and has_wing_pattern_solid and has_wing_pattern_multi_colored
17 -> has_bill_shape_all_purpose and has_bill_shape_cone and has_underparts_color_white and has_breast_pattern_striped and has_tail_shape_notched_tail and has_breast_color_white and has_throat_color_black and has_throat_color_buff and has_eye_color_black and has_bill_length_shorter_than_head and has_forehead_color_black and has_nape_color_black and has_nape_color_buff and has_belly_color_white and has_wing_shape_rounded-wings and has_size_small_(5_-_9_in) and has_shape_perching-like and has_back_pattern_striped and has_tail_pattern_solid and has_leg_color_grey and has_bill_color_buff and has_crown_color_black and has_wing_pattern_multi_colored

In [8]:
r = {}

for att in atts:
    r[att] = df[att]

In [9]:
df.describe()

,index,has_bill_shape_dagger,has_bill_shape_hooked_seabird,has_bill_shape_all-purpose,has_bill_shape_cone,has_wing_color_brown,has_wing_color_grey,has_wing_color_yellow,has_wing_color_black,has_wing_color_white,...,has_crown_color_brown,has_crown_color_grey,has_crown_color_yellow,has_crown_color_black,has_crown_color_white,has_wing_pattern_solid,has_wing_pattern_spotted,has_wing_pattern_striped,has_wing_pattern_multi-colored,class
count,11788.000000,11788.000000,11788.000000,11788.000000,11788.000000,11788.000000,11788.000000,11788.000000,11788.000000,11788.000000,...,11788.000000,11788.000000,11788.000000,11788.000000,11788.000000,11788.000000,11788.000000,11788.000000,11788.000000,11788.000000
mean,5894.500000,0.232016,0.094842,0.676111,0.447913,0.533424,0.696301,0.186546,0.870037,0.541907,...,0.382762,0.465643,0.100271,0.551748,0.175517,0.530285,0.094248,0.532151,0.715304,100.126315
std,3403.046821,0.422137,0.293009,0.467978,0.497301,0.498903,0.459874,0.389563,0.336277,0.498262,...,0.486082,0.498839,0.300374,0.497336,0.380425,0.499103,0.292186,0.498986,0.451289,57.476826
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2947.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,50.000000
50%,5894.500000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,100.000000
75%,8841.250000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,...,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,150.000000
max,11788.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,199.000000

In [12]:
r = {}

for att in atts:
    # if df[att].mean() > 0.55:
    #     continue
    # if df[att].mean() < 0.45:
    #     continue

    print(f"{att}")  #  -> {df[att].mean()}

    r[att] = df[att].mean()

has_bill_shape_dagger
has_bill_shape_hooked_seabird
has_bill_shape_all-purpose
has_bill_shape_cone
has_wing_color_brown
has_wing_color_grey
has_wing_color_yellow
has_wing_color_black
has_wing_color_white
has_wing_color_buff
has_upperparts_color_brown
has_upperparts_color_grey
has_upperparts_color_yellow
has_upperparts_color_black
has_upperparts_color_white
has_upperparts_color_buff
has_underparts_color_brown
has_underparts_color_grey
has_underparts_color_yellow
has_underparts_color_black
has_underparts_color_white
has_underparts_color_buff
has_breast_pattern_solid
has_breast_pattern_striped
has_breast_pattern_multi-colored
has_back_color_brown
has_back_color_grey
has_back_color_yellow
has_back_color_black
has_back_color_white
has_back_color_buff
has_tail_shape_notched_tail
has_upper_tail_color_brown
has_upper_tail_color_grey
has_upper_tail_color_black
has_upper_tail_color_white
has_upper_tail_color_buff
has_head_pattern_eyebrow
has_head_pattern_plain
has_breast_color_brown
has_breast_color_grey
has_breast_color_yellow
has_breast_color_black
has_breast_color_white
has_breast_color_buff
has_throat_color_grey
has_throat_color_yellow
has_throat_color_black
has_throat_color_white
has_throat_color_buff
has_eye_color_black
has_bill_length_about_the_same_as_head
has_bill_length_shorter_than_head
has_forehead_color_blue
has_forehead_color_brown
has_forehead_color_grey
has_forehead_color_yellow
has_forehead_color_black
has_forehead_color_white
has_under_tail_color_brown
has_under_tail_color_grey
has_under_tail_color_black
has_under_tail_color_white
has_under_tail_color_buff
has_nape_color_brown
has_nape_color_grey
has_nape_color_yellow
has_nape_color_black
has_nape_color_white
has_nape_color_buff
has_belly_color_brown
has_belly_color_grey
has_belly_color_yellow
has_belly_color_black
has_belly_color_white
has_belly_color_buff
has_wing_shape_rounded-wings
has_wing_shape_pointed-wings
has_size_small_(5_-_9_in)
has_size_medium_(9_-_16_in)
has_size_very_small_(3_-_5_in)
has_shape_duck-like
has_shape_perching-like
has_back_pattern_solid
has_back_pattern_striped
has_back_pattern_multi-colored
has_tail_pattern_solid
has_tail_pattern_striped
has_tail_pattern_multi-colored
has_belly_pattern_solid
has_primary_color_brown
has_primary_color_grey
has_primary_color_yellow
has_primary_color_black
has_primary_color_white
has_primary_color_buff
has_leg_color_grey
has_leg_color_black
has_leg_color_buff
has_bill_color_grey
has_bill_color_black
has_bill_color_buff
has_crown_color_blue
has_crown_color_brown
has_crown_color_grey
has_crown_color_yellow
has_crown_color_black
has_crown_color_white
has_wing_pattern_solid
has_wing_pattern_spotted
has_wing_pattern_striped
has_wing_pattern_multi-colored

In [2]:
len(r)

0

In [3]:
for k in r.keys():
    print(f"- {k.replace('-', '_')}")

In [58]:
for clazz in classes:
    is_set = []

    item = df_tmp.loc[clazz].head(1)
    for att in r.keys():
        if item[att].any() == 1:
            a = att.replace("multi-colored", "multi_colored").replace(
                "all-purpose", "all_purpose"
            )
            print(f'- "class={clazz} -> {a}"')
            # is_set.append(att.replace("multi-colored", "multi_colored").replace("all-purpose", "all_purpose"))

    # print(f"{clazz} -> {' and '.join(is_set)}")

- "class=0 -> has_upperparts_color_brown"
- "class=0 -> has_head_pattern_plain"
- "class=0 -> has_back_pattern_multi_colored"
- "class=0 -> has_primary_color_brown"
- "class=1 -> has_upperparts_color_brown"
- "class=1 -> has_upperparts_color_white"
- "class=1 -> has_head_pattern_plain"
- "class=1 -> has_primary_color_brown"
- "class=2 -> has_upper_tail_color_grey"
- "class=2 -> has_head_pattern_plain"
- "class=2 -> has_primary_color_brown"
- "class=3 -> has_head_pattern_plain"
- "class=3 -> has_nape_color_black"
- "class=3 -> has_leg_color_black"
- "class=4 -> has_nape_color_black"
- "class=5 -> has_upperparts_color_white"
- "class=5 -> has_nape_color_black"
- "class=5 -> has_leg_color_black"
- "class=6 -> has_upper_tail_color_grey"
- "class=6 -> has_head_pattern_plain"
- "class=6 -> has_nape_color_black"
- "class=7 -> has_upperparts_color_brown"
- "class=7 -> has_head_pattern_plain"
- "class=7 -> has_nape_color_black"
- "class=7 -> has_primary_color_brown"
- "class=8 -> has_head_pattern_plain"
- "class=8 -> has_nape_color_black"
- "class=8 -> has_leg_color_black"
- "class=9 -> has_head_pattern_plain"
- "class=9 -> has_nape_color_black"
- "class=9 -> has_leg_color_black"
- "class=10 -> has_upperparts_color_brown"
- "class=10 -> has_head_pattern_plain"
- "class=10 -> has_nape_color_black"
- "class=10 -> has_back_pattern_multi_colored"
- "class=10 -> has_primary_color_brown"
- "class=10 -> has_leg_color_black"
- "class=11 -> has_head_pattern_plain"
- "class=11 -> has_nape_color_black"
- "class=11 -> has_leg_color_black"
- "class=12 -> has_upperparts_color_white"
- "class=12 -> has_upper_tail_color_grey"
- "class=12 -> has_head_pattern_plain"
- "class=12 -> has_nape_color_black"
- "class=12 -> has_back_pattern_multi_colored"
- "class=12 -> has_leg_color_black"
- "class=13 -> has_upper_tail_color_grey"
- "class=13 -> has_head_pattern_plain"
- "class=13 -> has_back_pattern_multi_colored"
- "class=13 -> has_leg_color_black"
- "class=14 -> has_upperparts_color_white"
- "class=14 -> has_head_pattern_plain"
- "class=14 -> has_back_pattern_multi_colored"
- "class=14 -> has_leg_color_black"
- "class=15 -> has_head_pattern_plain"
- "class=15 -> has_back_pattern_multi_colored"
- "class=16 -> has_back_pattern_multi_colored"
- "class=17 -> has_nape_color_black"
- "class=18 -> has_upper_tail_color_grey"
- "class=18 -> has_head_pattern_plain"
- "class=18 -> has_leg_color_black"
- "class=19 -> has_upperparts_color_brown"
- "class=19 -> has_upper_tail_color_grey"
- "class=19 -> has_nape_color_black"
- "class=19 -> has_primary_color_brown"
- "class=19 -> has_leg_color_black"
- "class=20 -> has_upperparts_color_brown"
- "class=20 -> has_upperparts_color_white"
- "class=20 -> has_head_pattern_plain"
- "class=20 -> has_nape_color_black"
- "class=20 -> has_back_pattern_multi_colored"
- "class=20 -> has_primary_color_brown"
- "class=21 -> has_upperparts_color_brown"
- "class=21 -> has_nape_color_black"
- "class=21 -> has_primary_color_brown"
- "class=22 -> has_head_pattern_plain"
- "class=22 -> has_nape_color_black"
- "class=22 -> has_primary_color_brown"
- "class=22 -> has_leg_color_black"
- "class=23 -> has_head_pattern_plain"
- "class=23 -> has_nape_color_black"
- "class=23 -> has_leg_color_black"
- "class=24 -> has_head_pattern_plain"
- "class=24 -> has_nape_color_black"
- "class=24 -> has_leg_color_black"
- "class=25 -> has_head_pattern_plain"
- "class=25 -> has_nape_color_black"
- "class=25 -> has_leg_color_black"
- "class=26 -> has_head_pattern_plain"
- "class=26 -> has_nape_color_black"
- "class=26 -> has_leg_color_black"
- "class=27 -> has_upperparts_color_brown"
- "class=27 -> has_upperparts_color_white"
- "class=27 -> has_nape_color_black"
- "class=27 -> has_primary_color_brown"
- "class=28 -> has_head_pattern_plain"
- "class=28 -> has_nape_color_black"
- "class=28 -> has_leg_color_black"
- "class=29 -> has_head_pattern_plain"
- "class=29 -> has_nape_color_black"
- "class=29 -> has_leg_color_black"
- "class=30 -> has_upperparts_color_brown"
- "class=30 -> has_head_pattern_plain"
- "class=30 -> has_primary_color_brown"
- "class=30 -> has_leg_color_black"
- "class=31 -> has_upperparts_color_brown"
- "class=31 -> has_upper_tail_color_grey"
- "class=31 -> has_primary_color_brown"
- "class=32 -> has_upperparts_color_brown"
- "class=32 -> has_upper_tail_color_grey"
- "class=32 -> has_primary_color_brown"
- "class=33 -> has_upperparts_color_brown"
- "class=33 -> has_upper_tail_color_grey"
- "class=33 -> has_head_pattern_plain"
- "class=33 -> has_primary_color_brown"
- "class=33 -> has_leg_color_black"
- "class=34 -> has_upperparts_color_brown"
- "class=34 -> has_upperparts_color_white"
- "class=34 -> has_head_pattern_plain"
- "class=34 -> has_back_pattern_multi_colored"
- "class=34 -> has_primary_color_brown"
- "class=34 -> has_leg_color_black"
- "class=35 -> has_upperparts_color_brown"
- "class=35 -> has_primary_color_brown"
- "class=36 -> has_upperparts_color_brown"
- "class=36 -> has_upperparts_color_white"
- "class=36 -> has_upper_tail_color_grey"
- "class=36 -> has_head_pattern_plain"
- "class=36 -> has_primary_color_brown"
- "class=36 -> has_leg_color_black"
- "class=37 -> has_upperparts_color_brown"
- "class=37 -> has_upperparts_color_white"
- "class=37 -> has_head_pattern_plain"
- "class=37 -> has_back_pattern_multi_colored"
- "class=37 -> has_primary_color_brown"
- "class=37 -> has_leg_color_black"
- "class=38 -> has_upperparts_color_brown"
- "class=38 -> has_upperparts_color_white"
- "class=38 -> has_upper_tail_color_grey"
- "class=38 -> has_head_pattern_plain"
- "class=38 -> has_back_pattern_multi_colored"
- "class=38 -> has_primary_color_brown"
- "class=38 -> has_leg_color_black"
- "class=39 -> has_upperparts_color_brown"
- "class=39 -> has_upperparts_color_white"
- "class=39 -> has_upper_tail_color_grey"
- "class=39 -> has_head_pattern_plain"
- "class=39 -> has_nape_color_black"
- "class=39 -> has_back_pattern_multi_colored"
- "class=39 -> has_primary_color_brown"
- "class=39 -> has_leg_color_black"
- "class=40 -> has_upperparts_color_brown"
- "class=40 -> has_upperparts_color_white"
- "class=40 -> has_head_pattern_plain"
- "class=40 -> has_back_pattern_multi_colored"
- "class=40 -> has_leg_color_black"
- "class=41 -> has_upperparts_color_brown"
- "class=41 -> has_nape_color_black"
- "class=41 -> has_primary_color_brown"
- "class=41 -> has_leg_color_black"
- "class=42 -> has_upperparts_color_brown"
- "class=42 -> has_upperparts_color_white"
- "class=42 -> has_upper_tail_color_grey"
- "class=42 -> has_head_pattern_plain"
- "class=42 -> has_back_pattern_multi_colored"
- "class=42 -> has_primary_color_brown"
- "class=42 -> has_leg_color_black"
- "class=43 -> has_head_pattern_plain"
- "class=43 -> has_nape_color_black"
- "class=43 -> has_leg_color_black"
- "class=44 -> has_upperparts_color_white"
- "class=44 -> has_upper_tail_color_grey"
- "class=44 -> has_head_pattern_plain"
- "class=44 -> has_back_pattern_multi_colored"
- "class=45 -> has_upperparts_color_brown"
- "class=45 -> has_upperparts_color_white"
- "class=45 -> has_upper_tail_color_grey"
- "class=45 -> has_head_pattern_plain"
- "class=45 -> has_back_pattern_multi_colored"
- "class=45 -> has_primary_color_brown"
- "class=46 -> has_upperparts_color_white"
- "class=46 -> has_back_pattern_multi_colored"
- "class=47 -> has_upperparts_color_white"
- "class=47 -> has_nape_color_black"
- "class=47 -> has_back_pattern_multi_colored"
- "class=47 -> has_primary_color_brown"
- "class=48 -> has_head_pattern_plain"
- "class=48 -> has_nape_color_black"
- "class=48 -> has_back_pattern_multi_colored"
- "class=48 -> has_primary_color_brown"
- "class=48 -> has_leg_color_black"
- "class=49 -> has_upperparts_color_brown"
- "class=49 -> has_upper_tail_color_grey"
- "class=49 -> has_nape_color_black"
- "class=49 -> has_back_pattern_multi_colored"
- "class=49 -> has_primary_color_brown"
- "class=50 -> has_upperparts_color_brown"
- "class=50 -> has_upperparts_color_white"
- "class=50 -> has_upper_tail_color_grey"
- "class=50 -> has_nape_color_black"
- "class=50 -> has_back_pattern_multi_colored"
- "class=50 -> has_primary_color_brown"
- "class=51 -> has_upperparts_color_brown"
- "class=51 -> has_head_pattern_plain"
- "class=51 -> has_primary_color_brown"
- "class=52 -> has_upperparts_color_brown"
- "class=52 -> has_upperparts_color_white"
- "class=52 -> has_nape_color_black"
- "class=52 -> has_primary_color_brown"
- "class=53 -> has_upperparts_color_brown"
- "class=53 -> has_head_pattern_plain"
- "class=53 -> has_back_pattern_multi_colored"
- "class=53 -> has_leg_color_black"
- "class=54 -> has_upperparts_color_brown"
- "class=54 -> has_upperparts_color_white"
- "class=54 -> has_nape_color_black"
- "class=54 -> has_back_pattern_multi_colored"
- "class=54 -> has_primary_color_brown"
- "class=55 -> has_upperparts_color_white"
- "class=55 -> has_upper_tail_color_grey"
- "class=55 -> has_head_pattern_plain"
- "class=55 -> has_back_pattern_multi_colored"
- "class=55 -> has_leg_color_black"
- "class=56 -> has_upperparts_color_white"
- "class=56 -> has_head_pattern_plain"
- "class=56 -> has_nape_color_black"
- "class=56 -> has_back_pattern_multi_colored"
- "class=57 -> has_upperparts_color_white"
- "class=57 -> has_upper_tail_color_grey"
- "class=57 -> has_head_pattern_plain"
- "class=57 -> has_nape_color_black"
- "class=57 -> has_back_pattern_multi_colored"
- "class=58 -> has_upperparts_color_white"
- "class=58 -> has_upper_tail_color_grey"
- "class=58 -> has_head_pattern_plain"
- "class=58 -> has_back_pattern_multi_colored"
- "class=59 -> has_upperparts_color_white"
- "class=59 -> has_upper_tail_color_grey"
- "class=59 -> has_head_pattern_plain"
- "class=59 -> has_back_pattern_multi_colored"
- "class=60 -> has_upperparts_color_white"
- "class=60 -> has_upper_tail_color_grey"
- "class=60 -> has_head_pattern_plain"
- "class=60 -> has_back_pattern_multi_colored"
- "class=60 -> has_leg_color_black"
- "class=61 -> has_upperparts_color_white"
- "class=61 -> has_upper_tail_color_grey"
- "class=61 -> has_head_pattern_plain"
- "class=61 -> has_back_pattern_multi_colored"
- "class=62 -> has_upperparts_color_white"
- "class=62 -> has_head_pattern_plain"
- "class=62 -> has_leg_color_black"
- "class=63 -> has_upperparts_color_white"
- "class=63 -> has_upper_tail_color_grey"
- "class=63 -> has_head_pattern_plain"
- "class=64 -> has_upperparts_color_white"
- "class=64 -> has_upper_tail_color_grey"
- "class=64 -> has_head_pattern_plain"
- "class=64 -> has_back_pattern_multi_colored"
- "class=65 -> has_upperparts_color_white"
- "class=65 -> has_head_pattern_plain"
- "class=65 -> has_back_pattern_multi_colored"
- "class=66 -> has_primary_color_brown"
- "class=66 -> has_leg_color_black"
- "class=67 -> has_nape_color_black"
- "class=67 -> has_primary_color_brown"
- "class=67 -> has_leg_color_black"
- "class=68 -> has_upperparts_color_brown"
- "class=68 -> has_back_pattern_multi_colored"
- "class=68 -> has_primary_color_brown"
- "class=68 -> has_leg_color_black"
- "class=69 -> has_leg_color_black"
- "class=70 -> has_upper_tail_color_grey"
- "class=70 -> has_back_pattern_multi_colored"
- "class=70 -> has_primary_color_brown"
- "class=70 -> has_leg_color_black"
- "class=71 -> has_upperparts_color_brown"
- "class=71 -> has_upper_tail_color_grey"
- "class=71 -> has_head_pattern_plain"
- "class=71 -> has_primary_color_brown"
- "class=71 -> has_leg_color_black"
- "class=72 -> has_upperparts_color_white"
- "class=72 -> has_upper_tail_color_grey"
- "class=72 -> has_nape_color_black"
- "class=72 -> has_back_pattern_multi_colored"
- "class=72 -> has_leg_color_black"
- "class=73 -> has_head_pattern_plain"
- "class=73 -> has_back_pattern_multi_colored"
- "class=73 -> has_leg_color_black"
- "class=74 -> has_nape_color_black"
- "class=74 -> has_back_pattern_multi_colored"
- "class=75 -> has_upperparts_color_brown"
- "class=75 -> has_upper_tail_color_grey"
- "class=75 -> has_head_pattern_plain"
- "class=75 -> has_nape_color_black"
- "class=75 -> has_primary_color_brown"
- "class=76 -> has_upperparts_color_brown"
- "class=76 -> has_upper_tail_color_grey"
- "class=76 -> has_head_pattern_plain"
- "class=76 -> has_back_pattern_multi_colored"
- "class=76 -> has_primary_color_brown"
- "class=76 -> has_leg_color_black"
- "class=77 -> has_upperparts_color_brown"
- "class=77 -> has_upperparts_color_white"
- "class=77 -> has_upper_tail_color_grey"
- "class=77 -> has_head_pattern_plain"
- "class=77 -> has_primary_color_brown"
- "class=77 -> has_leg_color_black"
- "class=78 -> has_upper_tail_color_grey"
- "class=78 -> has_head_pattern_plain"
- "class=78 -> has_nape_color_black"
- "class=79 -> has_upperparts_color_white"
- "class=79 -> has_head_pattern_plain"
- "class=79 -> has_nape_color_black"
- "class=79 -> has_leg_color_black"
- "class=80 -> has_upperparts_color_white"
- "class=80 -> has_nape_color_black"
- "class=80 -> has_back_pattern_multi_colored"
- "class=80 -> has_leg_color_black"
- "class=81 -> has_upper_tail_color_grey"
- "class=81 -> has_head_pattern_plain"
- "class=82 -> has_upperparts_color_brown"
- "class=82 -> has_head_pattern_plain"
- "class=82 -> has_back_pattern_multi_colored"
- "class=82 -> has_primary_color_brown"
- "class=83 -> has_upperparts_color_white"
- "class=83 -> has_upper_tail_color_grey"
- "class=83 -> has_head_pattern_plain"
- "class=83 -> has_back_pattern_multi_colored"
- "class=84 -> has_upperparts_color_brown"
- "class=84 -> has_primary_color_brown"
- "class=84 -> has_leg_color_black"
- "class=85 -> has_upperparts_color_brown"
- "class=85 -> has_upperparts_color_white"
- "class=85 -> has_upper_tail_color_grey"
- "class=85 -> has_head_pattern_plain"
- "class=85 -> has_nape_color_black"
- "class=85 -> has_back_pattern_multi_colored"
- "class=85 -> has_primary_color_brown"
- "class=86 -> has_upperparts_color_brown"
- "class=86 -> has_upperparts_color_white"
- "class=86 -> has_head_pattern_plain"
- "class=86 -> has_nape_color_black"
- "class=86 -> has_back_pattern_multi_colored"
- "class=86 -> has_primary_color_brown"
- "class=87 -> has_upperparts_color_brown"
- "class=87 -> has_upperparts_color_white"
- "class=87 -> has_upper_tail_color_grey"
- "class=87 -> has_nape_color_black"
- "class=87 -> has_primary_color_brown"
- "class=88 -> has_upperparts_color_brown"
- "class=88 -> has_upperparts_color_white"
- "class=88 -> has_upper_tail_color_grey"
- "class=88 -> has_nape_color_black"
- "class=88 -> has_back_pattern_multi_colored"
- "class=88 -> has_primary_color_brown"
- "class=89 -> has_upperparts_color_white"
- "class=89 -> has_upper_tail_color_grey"
- "class=89 -> has_head_pattern_plain"
- "class=89 -> has_nape_color_black"
- "class=89 -> has_back_pattern_multi_colored"
- "class=89 -> has_primary_color_brown"
- "class=90 -> has_upperparts_color_brown"
- "class=90 -> has_upperparts_color_white"
- "class=90 -> has_upper_tail_color_grey"
- "class=90 -> has_head_pattern_plain"
- "class=90 -> has_back_pattern_multi_colored"
- "class=90 -> has_primary_color_brown"
- "class=90 -> has_leg_color_black"
- "class=91 -> has_upperparts_color_brown"
- "class=91 -> has_upperparts_color_white"
- "class=91 -> has_upper_tail_color_grey"
- "class=91 -> has_nape_color_black"
- "class=91 -> has_primary_color_brown"
- "class=92 -> has_upperparts_color_white"
- "class=92 -> has_head_pattern_plain"
- "class=92 -> has_back_pattern_multi_colored"
- "class=92 -> has_leg_color_black"
- "class=93 -> has_upperparts_color_white"
- "class=93 -> has_upper_tail_color_grey"
- "class=93 -> has_nape_color_black"
- "class=93 -> has_back_pattern_multi_colored"
- "class=93 -> has_leg_color_black"
- "class=94 -> has_upperparts_color_white"
- "class=94 -> has_head_pattern_plain"
- "class=94 -> has_nape_color_black"
- "class=94 -> has_back_pattern_multi_colored"
- "class=94 -> has_leg_color_black"
- "class=95 -> has_upperparts_color_white"
- "class=95 -> has_head_pattern_plain"
- "class=95 -> has_nape_color_black"
- "class=95 -> has_back_pattern_multi_colored"
- "class=95 -> has_leg_color_black"
- "class=96 -> has_upperparts_color_white"
- "class=96 -> has_head_pattern_plain"
- "class=96 -> has_nape_color_black"
- "class=96 -> has_back_pattern_multi_colored"
- "class=96 -> has_leg_color_black"
- "class=97 -> has_upperparts_color_white"
- "class=97 -> has_head_pattern_plain"
- "class=97 -> has_nape_color_black"
- "class=97 -> has_back_pattern_multi_colored"
- "class=98 -> has_upperparts_color_brown"
- "class=98 -> has_primary_color_brown"
- "class=99 -> has_upperparts_color_brown"
- "class=99 -> has_upperparts_color_white"
- "class=99 -> has_upper_tail_color_grey"
- "class=99 -> has_head_pattern_plain"
- "class=99 -> has_back_pattern_multi_colored"
- "class=99 -> has_primary_color_brown"
- "class=99 -> has_leg_color_black"
- "class=100 -> has_upperparts_color_white"
- "class=100 -> has_head_pattern_plain"
- "class=101 -> has_upperparts_color_brown"
- "class=101 -> has_upperparts_color_white"
- "class=101 -> has_upper_tail_color_grey"
- "class=101 -> has_head_pattern_plain"
- "class=101 -> has_back_pattern_multi_colored"
- "class=101 -> has_primary_color_brown"
- "class=101 -> has_leg_color_black"
- "class=102 -> has_upperparts_color_brown"
- "class=102 -> has_upperparts_color_white"
- "class=102 -> has_head_pattern_plain"
- "class=102 -> has_primary_color_brown"
- "class=102 -> has_leg_color_black"
- "class=103 -> has_upperparts_color_brown"
- "class=103 -> has_upper_tail_color_grey"
- "class=103 -> has_back_pattern_multi_colored"
- "class=103 -> has_primary_color_brown"
- "class=103 -> has_leg_color_black"
- "class=104 -> has_upperparts_color_brown"
- "class=104 -> has_upperparts_color_white"
- "class=104 -> has_upper_tail_color_grey"
- "class=104 -> has_nape_color_black"
- "class=104 -> has_primary_color_brown"
- "class=105 -> has_nape_color_black"
- "class=106 -> has_head_pattern_plain"
- "class=106 -> has_nape_color_black"
- "class=106 -> has_leg_color_black"
- "class=107 -> has_head_pattern_plain"
- "class=107 -> has_nape_color_black"
- "class=107 -> has_back_pattern_multi_colored"
- "class=107 -> has_leg_color_black"
- "class=108 -> has_head_pattern_plain"
- "class=108 -> has_nape_color_black"
- "class=108 -> has_back_pattern_multi_colored"
- "class=108 -> has_leg_color_black"
- "class=109 -> has_upperparts_color_brown"
- "class=109 -> has_upperparts_color_white"
- "class=109 -> has_upper_tail_color_grey"
- "class=109 -> has_nape_color_black"
- "class=109 -> has_primary_color_brown"
- "class=110 -> has_upperparts_color_white"
- "class=110 -> has_upper_tail_color_grey"
- "class=110 -> has_nape_color_black"
- "class=110 -> has_back_pattern_multi_colored"
- "class=110 -> has_leg_color_black"
- "class=111 -> has_upperparts_color_white"
- "class=111 -> has_upper_tail_color_grey"
- "class=111 -> has_nape_color_black"
- "class=111 -> has_back_pattern_multi_colored"
- "class=111 -> has_leg_color_black"
- "class=112 -> has_upperparts_color_brown"
- "class=112 -> has_nape_color_black"
- "class=112 -> has_primary_color_brown"
- "class=113 -> has_upperparts_color_brown"
- "class=113 -> has_upper_tail_color_grey"
- "class=113 -> has_nape_color_black"
- "class=113 -> has_back_pattern_multi_colored"
- "class=113 -> has_primary_color_brown"
- "class=113 -> has_leg_color_black"
- "class=114 -> has_upperparts_color_brown"
- "class=114 -> has_upper_tail_color_grey"
- "class=114 -> has_primary_color_brown"
- "class=115 -> has_upperparts_color_brown"
- "class=115 -> has_upperparts_color_white"
- "class=115 -> has_upper_tail_color_grey"
- "class=115 -> has_primary_color_brown"
- "class=116 -> has_upperparts_color_brown"
- "class=116 -> has_upperparts_color_white"
- "class=116 -> has_upper_tail_color_grey"
- "class=116 -> has_nape_color_black"
- "class=116 -> has_primary_color_brown"
- "class=117 -> has_upperparts_color_brown"
- "class=117 -> has_upper_tail_color_grey"
- "class=117 -> has_primary_color_brown"
- "class=118 -> has_upperparts_color_brown"
- "class=118 -> has_upperparts_color_white"
- "class=118 -> has_upper_tail_color_grey"